import React from 'react'
export const metadata = {
  title: 'Menu',
  description: 'Generated by create next app',
}
const page = () => {
  return (
    <div>Menu page</div>
  )
}

export default page