import { Inter } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css'
import { Toaster } from 'react-hot-toast'
import Link from 'next/link'
import NextTopLoader from 'nextjs-toploader';
import { ReduxProvider } from '@/redux/provider';
import Navbar from '@/components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  image: 'URL_TO_USER_IMAGE', // Replace 'URL_TO_USER_IMAGE' with the URL of the user's image

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color='red' showSpinner={false} />
        <Toaster />
        <ReduxProvider>
          <Navbar />
          {children}
          <SpeedInsights />
        </ReduxProvider>
      </body>
    </html>
  )
}
