import { Inter } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css'
import { Toaster } from 'react-hot-toast'
import Link from 'next/link'
import NextTopLoader from 'nextjs-toploader';
import { ReduxProvider } from '@/redux/provider';
import Navbar from '@/components/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="google-adsense-account" content="ca-pub-4815404807688326"></meta>
      <head><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4815404807688326"
        crossOrigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <NextTopLoader color='red' showSpinner={false} />
        <Toaster />
        <ReduxProvider>
          <Navbar />
          {children}
          <SpeedInsights />
        </ReduxProvider>
      </body>
    </html>
  )
}
