import OtpForm from "@/components/OtpForm/page";
export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default async function Home() {

  return (
    <>
    <div className="">Home Page</div>
    </>
  )
};