import Profile from "@/components/Profile/Profile";
export const metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/125.gif',
        href: '/edit-profile',
      }
    ],
    // apple: ["/cross.png"],
    // shortcut: ["/125.gif"]
  }
}
export default function UserProfileEdit() {
  return (
    <>
      <Profile />
    </>
  );
};