import Profile from "@/components/Profile/Profile";
export const metadata = {
  title: 'Profile',
  description: 'Generated by create next app',
  icons: {
    icon: ["/125.gif"],
    apple: ["/cross.png"],
    shortcut: ["/125.gif"]
  }
}
export default function UserProfileEdit() {
  return (
    <>
      <Profile />
    </>
  );
};